# Site settings
title: Kamal's Javascript Regrets
email: kamalasaurus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  regret (n.) – 1. pain or distress in the mind at something done or left undone
  Kamal has many regrets. Mostly Javascript related.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kamalasaurus
github_username:  kamalasaurus

# Build settings
markdown: kramdown
