# Site settings
title: Javascriptrix
email: kamalasaurus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sometimes it helps to write things down.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kamalasaurus
github_username:  kamalasaurus

# Build settings
markdown: kramdown
